spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
